### ISSUE TITLE
Duplicate Enum FestaStatus

### ISSUE THREAD

**Issue by AngeloDotNet** [AngeloDotNet/GestioneSagreWeb#54]

**Comment by NetDevForLife** [comment]
To reduce code duplication, you could think about creating an ad hoc library or reading data from a table in the database

**Comment by AngeloDotNet** [comment]
This bug will be fixed in version 2.0 of the application, taking @NetDevForLife's suggestion into consideration

**Comment by AngeloDotNet** [comment]
> To reduce code duplication, you could think about creating an ad hoc library or reading data from a table in the database

Thank you for your suggestion
